import os


class Config:
    SECRET_KEY = os.getenv("SECRET_KEY", "dev-secret-key")
    SQLALCHEMY_DATABASE_URI = os.getenv("DATABASE_URL", "sqlite:///aureline.db")
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    MAIL_SERVER = os.getenv("MAIL_SERVER")
    MAIL_PORT = int(os.getenv("MAIL_PORT", 587))
    MAIL_USE_TLS = os.getenv("MAIL_USE_TLS", "true").lower() == "true"
    MAIL_USERNAME = os.getenv("MAIL_USERNAME")
    MAIL_PASSWORD = os.getenv("MAIL_PASSWORD")
    MAIL_DEFAULT_SENDER = os.getenv("MAIL_DEFAULT_SENDER") or os.getenv("MAIL_USERNAME")
    ADMIN_ALERT_EMAIL = os.getenv("ADMIN_ALERT_EMAIL") or os.getenv("MAIL_USERNAME")
    ZOOM_CLIENT_ID = os.getenv("ZOOM_CLIENT_ID")
    ZOOM_CLIENT_SECRET = os.getenv("ZOOM_CLIENT_SECRET")
    ZOOM_ACCOUNT_ID = os.getenv("ZOOM_ACCOUNT_ID")
    ZOOM_REDIRECT_URI = os.getenv("ZOOM_REDIRECT_URI")
    ZOOM_WEBHOOK_SECRET_TOKEN = os.getenv("ZOOM_WEBHOOK_SECRET_TOKEN")
    APP_BASE_URL = os.getenv("APP_BASE_URL", "http://localhost:5000")
    META_VERIFY_TOKEN = os.getenv("META_VERIFY_TOKEN")
    META_APP_SECRET = os.getenv("META_APP_SECRET")
    WHATSAPP_PHONE_NUMBER_ID = os.getenv("WHATSAPP_PHONE_NUMBER_ID")
    WHATSAPP_ACCESS_TOKEN = os.getenv("WHATSAPP_ACCESS_TOKEN")
    MESSENGER_PAGE_ACCESS_TOKEN = os.getenv("MESSENGER_PAGE_ACCESS_TOKEN")
    MESSENGER_PAGE_ID = os.getenv("MESSENGER_PAGE_ID")
    AURELINE_NOTIFY_WHATSAPP = os.getenv("AURELINE_NOTIFY_WHATSAPP")
    BKASH_BASE_URL = os.getenv("BKASH_BASE_URL")
    BKASH_APP_KEY = os.getenv("BKASH_APP_KEY")
    BKASH_APP_SECRET = os.getenv("BKASH_APP_SECRET")
    BKASH_USERNAME = os.getenv("BKASH_USERNAME")
    BKASH_PASSWORD = os.getenv("BKASH_PASSWORD")
    NAGAD_BASE_URL = os.getenv("NAGAD_BASE_URL")
    NAGAD_MERCHANT_ID = os.getenv("NAGAD_MERCHANT_ID")
    NAGAD_PUBLIC_KEY = os.getenv("NAGAD_PUBLIC_KEY")
    NAGAD_PRIVATE_KEY = os.getenv("NAGAD_PRIVATE_KEY")
    BKASH_PAYMENT_URL = os.getenv("BKASH_PAYMENT_URL")
    BKASH_PAY_TO = os.getenv("BKASH_PAY_TO", "01XXXXXXXXX")
    BKASH_ACCOUNT_NAME = os.getenv("BKASH_ACCOUNT_NAME", "Aureline Academy")
    NAGAD_PAYMENT_URL = os.getenv("NAGAD_PAYMENT_URL")
    NAGAD_PAY_TO = os.getenv("NAGAD_PAY_TO", "01XXXXXXXXX")
    NAGAD_ACCOUNT_NAME = os.getenv("NAGAD_ACCOUNT_NAME", "Aureline Academy")
    CARD_PAYMENT_URL = os.getenv("CARD_PAYMENT_URL", "https://example.com/aureline-payment")
    CARD_ACCOUNT_NAME = os.getenv("CARD_ACCOUNT_NAME", "Aureline Academy Online Payments")
    BANK_PAYMENT_URL = os.getenv("BANK_PAYMENT_URL")
    BANK_ACCOUNT_NAME = os.getenv("BANK_ACCOUNT_NAME", "Aureline Academy")
    BANK_ACCOUNT_NUMBER = os.getenv("BANK_ACCOUNT_NUMBER", "0000000000000")
    SMS_API_URL = os.getenv("SMS_API_URL")
    SMS_API_KEY = os.getenv("SMS_API_KEY")
    SMS_SENDER_ID = os.getenv("SMS_SENDER_ID")
    REDIS_URL = os.getenv("REDIS_URL", "redis://localhost:6379/0")
    FAQ_SUPPORTED_LANGUAGES = ["en", "bn"]
    WTF_CSRF_TIME_LIMIT = None
    MAX_CONTENT_LENGTH = int(os.getenv("MAX_CONTENT_LENGTH", 8 * 1024 * 1024))
    PAYMENT_SLIP_UPLOAD_FOLDER = os.getenv("PAYMENT_SLIP_UPLOAD_FOLDER", "payment_slips")
    PROFILE_UPLOAD_FOLDER = os.getenv("PROFILE_UPLOAD_FOLDER", "profile_photos")
