"""student dashboard exports and reminders

Revision ID: 55ff59e994f6
Revises: d9f1a2b3c4d5
Create Date: 2026-04-12 09:06:06.161890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55ff59e994f6'
down_revision = 'd9f1a2b3c4d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_test_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('test_title', sa.String(length=150), nullable=False),
    sa.Column('total_marks', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('obtained_marks', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profile.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('billing_month', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('reminder_sent_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_invoice_billing_month'), ['billing_month'], unique=False)
        batch_op.create_foreign_key('fk_invoice_course_id', 'course', ['course_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_constraint('fk_invoice_course_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_invoice_billing_month'))
        batch_op.drop_column('reminder_sent_at')
        batch_op.drop_column('billing_month')
        batch_op.drop_column('course_id')

    op.drop_table('class_test_result')
    # ### end Alembic commands ###
