"""initial schema

Revision ID: 63962d2ff6ef
Revises: 
Create Date: 2026-04-11 07:11:09.131142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63962d2ff6ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_inquiry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visitor_name', sa.String(length=120), nullable=True),
    sa.Column('visitor_email', sa.String(length=120), nullable=True),
    sa.Column('visitor_mobile', sa.String(length=20), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('library_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('author', sa.String(length=120), nullable=False),
    sa.Column('isbn', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('shelf', sa.String(length=40), nullable=True),
    sa.Column('published_year', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('copies_total', sa.Integer(), nullable=False),
    sa.Column('copies_available', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn')
    )
    op.create_table('notice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('audience', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('published_on', sa.Date(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)

    op.create_table('student_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admission_no', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=50), nullable=False),
    sa.Column('section', sa.String(length=20), nullable=True),
    sa.Column('guardian_name', sa.String(length=120), nullable=True),
    sa.Column('guardian_phone', sa.String(length=20), nullable=True),
    sa.Column('parent_email', sa.String(length=120), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('fee_status', sa.String(length=30), nullable=False),
    sa.Column('progress_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('student_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_profile_admission_no'), ['admission_no'], unique=True)

    op.create_table('teacher_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('subject_specialty', sa.String(length=120), nullable=True),
    sa.Column('qualification', sa.String(length=120), nullable=True),
    sa.Column('join_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('teacher_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_profile_employee_id'), ['employee_id'], unique=True)

    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('class_name', sa.String(length=50), nullable=False),
    sa.Column('room', sa.String(length=50), nullable=True),
    sa.Column('schedule_text', sa.String(length=120), nullable=True),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('zoom_meeting_id', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_code'), ['code'], unique=True)

    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_no', sa.String(length=50), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('payment_provider', sa.String(length=30), nullable=True),
    sa.Column('payment_method', sa.String(length=30), nullable=True),
    sa.Column('transaction_ref', sa.String(length=120), nullable=True),
    sa.Column('paid_on', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_invoice_no'), ['invoice_no'], unique=True)

    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attended_on', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_id', 'attended_on', name='uq_attendance_student_course_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance')
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_invoice_no'))

    op.drop_table('invoice')
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_code'))

    op.drop_table('course')
    with op.batch_alter_table('teacher_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_profile_employee_id'))

    op.drop_table('teacher_profile')
    with op.batch_alter_table('student_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_profile_admission_no'))

    op.drop_table('student_profile')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_role'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('notice')
    op.drop_table('library_book')
    op.drop_table('chat_inquiry')
    # ### end Alembic commands ###
